apiVersion: apps/v1
kind: Deployment
metadata:
  name:  devopsdummy-laravel-holalaravel-mfe-frontend-deployment
  namespace: devopsdummy
  labels:
    app:  devopsdummy-laravel-holalaravel-mfe
spec:
  selector:
    matchLabels:
      app: devopsdummy-laravel-holalaravel-mfe
  replicas: 1
  template:
    metadata:
      labels:
        app: devopsdummy-laravel-holalaravel-mfe
    spec:
      serviceAccountName: sa-devopsdummy
      containers:
      - name:  devopsdummy-laravel-holalaravel-mfe-frontend
        image:  alcaldiadevopsdummy.azurecr.io/devopsdummy-laravel-holalaravel-mfe-frontend-preprod:latest
        lifecycle:
          postStart:
            exec:
              command:
              - /bin/sh
              - -c
              - |
                php artisan migrate --force
        readinessProbe:
          tcpSocket:
            port: 8009
          initialDelaySeconds: 60
          timeoutSeconds: 3
          periodSeconds: 10
          failureThreshold: 3
        resources:
          requests:
            cpu: 100m #consumo de cpu del servicio
            memory: 100Mi #consumo de memory del servicio
          limits:
            cpu: 100m
            memory: 2500Mi
        ports:
        - containerPort:  8009