apiVersion: apps/v1
kind: Deployment
metadata:
  name:  holavite
  namespace: devopsdummy
  labels:
    app:  holavite
    tecnologia: react
    tipo: frontend
spec:
  selector:
    matchLabels:
      app: holavite
  replicas: 1
  template:
    metadata:
      labels:
        app:  holavite
        tecnologia: react
        tipo: frontend
    spec:
      serviceAccountName: sa-devopsdummy
      containers:
      - name:  holavite
        image:  alcaldiadevopsdummy.azurecr.io/devopsdummy-react-holavite-mfe-frontend-preprod:latest
        resources:
          requests:
            cpu: 100m #consumo de cpu del servicio
            memory: 100Mi #consumo de memory del servicio
          limits:
            cpu: 100m
            memory: 2500Mi
        ports:
        - containerPort:  3000