name: $(SourceBranchName)_$(Build.BuildId)

trigger:
  batch: true
  branches:
    include:
      - main
      - preprod
  paths:
    exclude:
      - deployments/*
      - README.md
      - .gitignore

resources:
  repositories:
    - repository: infraestructura
      type: git
      name: devops-pipeline-openshiftApply
      ref: refs/heads/preprod

stages:
  - template: master-azure-pipelines.yaml@infraestructura
