apiVersion: v1
kind: Service
metadata:
  name:  devopsdummy-laravel-holalaravel-mfe-frontend-service
  namespace: devopsdummy
  labels:
    app:  devopsdummy
    tecnologia: laravel
    tipo: frontend
spec:  
  selector:
    app: devopsdummy
  ports:
  - port: 8009
    protocol: TCP
    targetPort: 8009